### ISSUE TITLE
Unable to locate binaries

### ISSUE THREAD

**Issue by aaronfay** [UAlbertaALTLab/homebrew-hfst#1]
After an install of the package I cannot locate the `hfst-*` executables:

```
❯ brew install ualbertaaltlab/hfst/hfst
Warning: ualbertaaltlab/hfst/hfst 3.15.0 is already installed and up-to-date
To reinstall 3.15.0, run `brew reinstall hfst`

~
❯ hfst
zsh: command not found: hfst

```

**Comment by aaronfay** [comment]
Btw they are installed in `/usr/local/Cellar/hfst/3.15.0/bin/`, I will add that to my `PATH` however I would assume that would be handled somehow by the install script. @eddieantonio what am I missing here?

**Comment by eddieantonio** [comment]
Hey @aaronfay! I happened to notice that when you first tried to uninstall `hfst`, it said that Homebrew was not managing it. I _think_ what happened is that you manually installed `hfst` in the correct directories a while ago, HOWEVER, you then installed with Homebrew using `ualbertaaltlab/hfst/hfst`. So when you installed the brew managed one, brew chickened out and gave you a message like this:

```
Linking /usr/local/Cellar/hfst/3.15.0...
Error: Could not symlink bin/hfst-lookup
Target /usr/local/bin/hfst-lookup
already exists. You may want to remove it:
  rm '/usr/local/bin/hfst-lookup'

To force the link and overwrite all conflicting files:
  brew link --overwrite hfst

To list all files that would be deleted:
  brew link --overwrite --dry-run hfst
```

If this is indeed the problem, then the solution is this:

```sh
brew link --overwrite hfst
```

Then you should be able to run:

```sh
hfst-optimized-lookup --help
```

**Comment by aaronfay** [comment]
I tried a `brew uninstall hfst` and got a message saying there was not package installed by that name, so I just plowed ahead. I set up the links manually and it's fine now. 

Thanks for the help.
